### ISSUE TITLE
copy test suite to other project raises nil exception

### ISSUE THREAD

**Issue by cforce** [kawasima/redmine_impasse#165]
redmine 2.1.4
impasse trunk
jruby 1.7

I created a test suite witrh two test cases and selected it. Then i tried to copy that to another project with redmine impasse enabled (btw. the project list shall only show projects with module redmine impasse enabled, this would be error prone)

Then i got an internal exception.

NoMethodError (undefined method `each' for nil:NilClass):
  plugins/redmine_impasse/app/controllers/impasse_test_case_controller.rb:184:in`copy_to_another_project'
  org/jruby/RubyBasicObject.java:1667:in `__send__'
  org/jruby/RubyKernel.java:2077:in`send'
  actionpack (3.2.8) lib/action_controller/metal/implicit_render.rb:4:in `send_action'
  actionpack (3.2.8) lib/abstract_controller/base.rb:167:in`process_action'
  actionpack (3.2.8) lib/action_controller/metal/rendering.rb:10:in `process_action'
  actionpack (3.2.8) lib/abstract_controller/callbacks.rb:18:in`process_action'
  activesupport (3.2.8) lib/active_support/callbacks.rb:483:in `_run__785544915__process_action__1516380442__callbacks'
  org/jruby/RubyBasicObject.java:1667:in`**send**'
  org/jruby/RubyKernel.java:2077:in `send'
  activesupport (3.2.8) lib/active_support/callbacks.rb:405:in`**run_callback'
  activesupport (3.2.8) lib/active_support/callbacks.rb:390:in `_run_process_action_callbacks'
  org/jruby/RubyBasicObject.java:1673:in`__send**'
  org/jruby/RubyKernel.java:2081:in `send'
  activesupport (3.2.8) lib/active_support/callbacks.rb:81:in`run_callbacks'
  actionpack (3.2.8) lib/abstract_controller/callbacks.rb:17:in `process_action'
  actionpack (3.2.8) lib/action_controller/metal/rescue.rb:29:in`process_action'
  actionpack (3.2.8) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
  activesupport (3.2.8) lib/active_support/notifications.rb:123:in`instrument'
  activesupport (3.2.8) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  activesupport (3.2.8) lib/active_support/notifications/instrumenter.rb:19:in`instrument'
  activesupport (3.2.8) lib/active_support/notifications.rb:123:in `instrument'
  actionpack (3.2.8) lib/action_controller/metal/instrumentation.rb:29:in`process_action'
  actionpack (3.2.8) lib/action_controller/metal/params_wrapper.rb:207:in `process_action'
  activerecord (3.2.8) lib/active_record/railties/controller_runtime.rb:18:in`process_action'
  actionpack (3.2.8) lib/abstract_controller/base.rb:121:in `process'
  actionpack (3.2.8) lib/abstract_controller/rendering.rb:45:in`process'
  actionpack (3.2.8) lib/action_controller/metal.rb:203:in `dispatch'
  actionpack (3.2.8) lib/action_controller/metal/rack_delegation.rb:14:in`dispatch'
  actionpack (3.2.8) lib/action_controller/metal.rb:246:in `action'
  org/jruby/RubyProc.java:249:in`call'
  actionpack (3.2.8) lib/action_dispatch/routing/route_set.rb:73:in `dispatch'
  actionpack (3.2.8) lib/action_dispatch/routing/route_set.rb:36:in`call'
  journey (1.0.4) lib/journey/router.rb:68:in `call'
  org/jruby/RubyArray.java:1612:in`each'
  journey (1.0.4) lib/journey/router.rb:56:in `call'
  actionpack (3.2.8) lib/action_dispatch/routing/route_set.rb:600:in`call'
  rack-openid (1.3.1) lib/rack/openid.rb:98:in `call'
  actionpack (3.2.8) lib/action_dispatch/middleware/best_standards_support.rb:17:in`call'
  rack (1.4.1) lib/rack/etag.rb:23:in `call'
  rack (1.4.1) lib/rack/conditionalget.rb:35:in`call'
  actionpack (3.2.8) lib/action_dispatch/middleware/head.rb:14:in `call'
  actionpack (3.2.8) lib/action_dispatch/middleware/params_parser.rb:21:in`call'
  plugins/redmine_dmsf/lib/redmine_dmsf/webdav/no_parse.rb:33:in `call'
  actionpack (3.2.8) lib/action_dispatch/middleware/flash.rb:242:in`call'
  rack (1.4.1) lib/rack/session/abstract/id.rb:205:in `context'
  rack (1.4.1) lib/rack/session/abstract/id.rb:200:in`call'
  actionpack (3.2.8) lib/action_dispatch/middleware/cookies.rb:339:in `call'
  activerecord (3.2.8) lib/active_record/query_cache.rb:64:in`call'
  activerecord (3.2.8) lib/active_record/connection_adapters/abstract/connection_pool.rb:473:in `call'
  actionpack (3.2.8) lib/action_dispatch/middleware/callbacks.rb:28:in`call'
  activesupport (3.2.8) lib/active_support/callbacks.rb:408:in `_run__134017539__call__31777764__callbacks'
  org/jruby/RubyBasicObject.java:1667:in`**send**'
  org/jruby/RubyKernel.java:2077:in `send'
  activesupport (3.2.8) lib/active_support/callbacks.rb:405:in`**run_callback'
  activesupport (3.2.8) lib/active_support/callbacks.rb:390:in `_run_call_callbacks'
  org/jruby/RubyBasicObject.java:1667:in`__send**'
  org/jruby/RubyKernel.java:2077:in `send'
  activesupport (3.2.8) lib/active_support/callbacks.rb:81:in`run_callbacks'
  actionpack (3.2.8) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
  actionpack (3.2.8) lib/action_dispatch/middleware/remote_ip.rb:31:in`call'
  actionpack (3.2.8) lib/action_dispatch/middleware/debug_exceptions.rb:16:in `call'
  actionpack (3.2.8) lib/action_dispatch/middleware/show_exceptions.rb:56:in`call'
  railties (3.2.8) lib/rails/rack/logger.rb:26:in `call_app'
  railties (3.2.8) lib/rails/rack/logger.rb:16:in`call'
  actionpack (3.2.8) lib/action_dispatch/middleware/request_id.rb:22:in `call'
  rack (1.4.1) lib/rack/methodoverride.rb:21:in`call'
  rack (1.4.1) lib/rack/runtime.rb:17:in `call'
  activesupport (3.2.8) lib/active_support/cache/strategy/local_cache.rb:72:in`call'
  rack (1.4.1) lib/rack/lock.rb:15:in `call'
  actionpack (3.2.8) lib/action_dispatch/middleware/static.rb:62:in`call'
  rack-cache (1.2) lib/rack/cache/context.rb:136:in `forward'
  rack-cache (1.2) lib/rack/cache/context.rb:143:in`pass'
  rack-cache (1.2) lib/rack/cache/context.rb:155:in `invalidate'
  rack-cache (1.2) lib/rack/cache/context.rb:71:in`call!'
  rack-cache (1.2) lib/rack/cache/context.rb:51:in `call'
  railties (3.2.8) lib/rails/engine.rb:479:in`call'
  railties (3.2.8) lib/rails/application.rb:223:in `call'
  rack (1.4.1) lib/rack/content_length.rb:14:in`call'
  railties (3.2.8) lib/rails/rack/log_tailer.rb:17:in `call'
  rack (1.4.1) lib/rack/handler/webrick.rb:59:in`service'
  /home/sidfunktion/.rvm/rubies/jruby-1.7.0/lib/ruby/1.9/webrick/httpserver.rb:138:in `service'
  /home/sidfunktion/.rvm/rubies/jruby-1.7.0/lib/ruby/1.9/webrick/httpserver.rb:94:in`run'
  /home/sidfunktion/.rvm/rubies/jruby-1.7.0/lib/ruby/1.9/webrick/httpserver.rb:72:in `run'
  /home/sidfunktion/.rvm/rubies/jruby-1.7.0/lib/ruby/1.9/webrick/server.rb:191:in`start_thread'
  /home/sidfunktion/.rvm/rubies/jruby-1.7.0/lib/ruby/1.9/webrick/server.rb:181:in `start_thread'

**Comment by pazion** [comment]
Same error here.

I am not familiair with Ruby on rails, but tried to add a check wether the for each var (params[:node_ids] ) exists on line 184 of plugins/redmine_impasse/app/controllers/impasse_test_case_controller.rb.

Although error does not occur any more and it says saved, nothing is copied.
