### ISSUE TITLE
Internal error

### ISSUE THREAD

**Issue by dol916** [kawasima/redmine_impasse#201]
How are you?
I use "bitnami-redmine-2.2.3-0-windows-installer" & "impasse".
When one project is opened and the other projects are closed, there is no problem.

But, when two or more projects are opened, if "tests" is clicked, it occurs following error.

"Internal error
An error occurred on the page you were trying to access.
 If you continue to experience problems please contact your Redmine administrator for assistance.
If you are the Redmine administrator, check your log files for details about the error."

I would like to know how I solve this problem, or contingency action.
Thank you so much.

**Comment by smiodus** [comment]
I have same problem but not under bitnami env. Please keep impasse live.

**Comment by voodoo144** [comment]
I have the same error

**Comment by cforce** [comment]
seems to be dead ;/

**Comment by voodoo144** [comment]
((((

**Comment by carstencodes** [comment]
Same for me

From my production log, I see the following:

ActionView::Template::Error (undefined method `labelled_tabular_form_for' for #<#Class:0xe4322a3c:0xe431f5d0>):
    103:            </p>
    104:          <% end %>
    105:        <% else %>
    106:           <% output = labelled_tabular_form_for @project, :as => :copy_tests, :url => { :action => :copy_to_another_project } do |f| %>
    107:            <p>
    108:              <label for="dest_project_id"><%= l(:field_project) %></label>
    109:              <%= select_tag('dest_project_id', project_tree_options_for_select(@allowed_projects, :selected => @target_project)) %>

**Comment by cforce** [comment]
Check https://github.com/cforce/redmine_impasse@develop

**Comment by rafraf10** [comment]
I have facing the same problem too. :(

Tried the develop branch and the hotfix/1.2.3 branch does not solve the problem.

I am still getting interval error with: undefined method `labelled_tabular_form_for' error.

Any idea how to solve it?

**Comment by rafraf10** [comment]
I managed to solve my problem...

The page "plugins/redmine_impasse/app/views/impasse_test_case/index.html.erb" is not able to get the correct version the rails installation due to some permission problem (as my redmine is running on ubuntu).

When I tried to execute "rails" command as a normal user (without the sudo option) I always get permission error reading some Gem files liek below:
user1@server1:/usr/local/share/redmine/log$ rails --version
/usr/local/share/redmine-2.1.2/Gemfile:93:in `read': Permission denied - /usr/local/share/redmine-2.1.2/plugins/redmine_knowledgebase/Gemfile (Errno::EACCES)
        from /usr/local/share/redmine-2.1.2/Gemfile:93:in`eval_gemfile'
        from /usr/local/share/redmine-2.1.2/Gemfile:91:in `glob'
        from /usr/local/share/redmine-2.1.2/Gemfile:91:in`eval_gemfile'
        from /var/lib/gems/1.8/gems/bundler-1.2.4/lib/bundler/dsl.rb:7:in `evaluate'
        from /var/lib/gems/1.8/gems/bundler-1.2.4/lib/bundler/definition.rb:18:in`build'
        from /var/lib/gems/1.8/gems/bundler-1.2.4/lib/bundler.rb:144:in `definition'
        from /var/lib/gems/1.8/gems/bundler-1.2.4/lib/bundler.rb:112:in`setup'
        from /var/lib/gems/1.8/gems/bundler-1.2.4/lib/bundler/setup.rb:7
        from /usr/lib/ruby/vendor_ruby/1.8/rubygems/custom_require.rb:59:in `gem_original_require'
        from /usr/lib/ruby/vendor_ruby/1.8/rubygems/custom_require.rb:59:in`require'
        from /usr/local/share/redmine-2.1.2/config/boot.rb:6
        from script/rails:5:in `require'

After granting read option to all users on the Gem files, miraculously the internal error issue is gone.

Hope it will you to solve the issue.
